name: CFN-NAG Security Scan

on: [push]

## set the env var to be used across jobs
env:
  CLOUDFORMATION_DIRECTORY: "./cloudformation/"

jobs:
  ## cfn-nag security scan
  security-scan-nag:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: grolston/cfn-security@master
      with:
        scanner: "cfn-nag"
        cloudformation_directory: ${CLOUDFORMATION_DIRECTORY}
  ## checkov security scan
  security-scan-checkov:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: grolston/cfn-security@master
      with:
        scanner: "checkov"
        cloudformation_directory: ${CLOUDFORMATION_DIRECTORY}