name: CFN-NAG Security Scan

on: [push]

jobs:
  security-scan-nag:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: grolston/cfn-security@master
      env:
        CLOUDFORMATION_DIRECTORY: "./cloudformation/"
        TEST: "cfn-nag"