name: Checkov Security Scan

on: [push]

jobs:
  ## checkov security scan
  security-scan-checkov:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: grolston/cfn-security@master
      with:
        cloudformation_directory: './cloudformation/' ## change to your template directory
        scanner: "checkov"